Feature/vijay common slider
HighVibe/hvn pull request #348
Opened 2020-08-20 13:40 UTC by mob-dev

- Create & update common slider

2020-08-31 06:54 UTC, AlexVegner requested changes

2020-08-31 06:54 UTC, AlexVegner commented on mobile/lib/modules/audio_player/widgets/audio_player_slider.dart
> +import 'package:flutter_xlider/flutter_xlider.dart';
Please flollow task https://github.com/HighVibe/hvn/issues/338
Move file to 
core/lib/widgets/sliders/common_slider.dart

Change class name to CommonSlider

2020-09-02 14:04 UTC, mob-dev commented on mobile/lib/modules/audio_player/widgets/audio_player_slider.dart
> +import 'package:flutter_xlider/flutter_xlider.dart';
I have used the **flutter_xlider** package so I will not be able to change the import statement.

2020-09-07 15:22 UTC, AlexVegner requested changes

2020-09-07 15:22 UTC, AlexVegner commented on mobile/pubspec.yaml
> +  flutter_xlider: ^3.4.0
add it only to core or mobile + web 
mobile and web depends from code

2020-09-07 15:22 UTC, AlexVegner commented on web/pubspec.yaml
> +  flutter_xlider: ^3.4.0
add it only to core or mobile + web
mobile and web depends from code

2020-09-14 07:08 UTC, AlexVegner approved these changes

2020-09-14 07:58 UTC, merged