Create common action buttons
HighVibe/hvn pull request #350
Opened 2020-08-21 11:44 UTC by mob-dev

- Create common action buttons

┆Issue is synchronized with this [Jira Task](https://highvibe.atlassian.net/browse/HVN1-205) by [Unito](https://www.unito.io/learn-more)

2020-08-31 07:05 UTC, AlexVegner requested changes

2020-08-31 07:05 UTC, AlexVegner commented on mobile/lib/widgets/buttons/common_action_button.dart
> +class AppBarButtons {
Please follow task https://github.com/HighVibe/hvn/issues/342

- [ ] Move task to core/lib/widgets/buttons/common_action_button.dart

- [ ] Rename with CommonActionButton

- [ ] We need to have reusable widget. 

AppBarButtons(). back(...) looks ugly. 
Please use main widget constructor + Factory constructors which use defoault costructor. 
But we need a widget which have one animation for all cases

2020-09-10 10:20 UTC, AlexVegner requested changes

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/home/home_page.dart
> +                      icon: SvgPicture.asset(Assets.svg.icHamburger) ,
Please format the code properly, unnesesary space  `) ,` should be `),`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/home/home_page.dart
> +                          icon: SvgPicture.asset(Assets.svg.icTheme) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/home/home_page.dart
> +                 /*   AppBarButtons().drawer(
Remove commented code

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/home/home_page.dart
> +                  /*      AppBarButtons().themes(
Remove commented code

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/home/home_page.dart
> +                          icon: SvgPicture.asset(Assets.svg.icWallet) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/home/home_page.dart
> +                   /*     AppBarButtons().wallet(onPressed: () {
Remove commented code

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/home/home_page.dart
> +                          icon: SvgPicture.asset(Assets.svg.icNotification) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/home/home_page.dart
> +                          onClickCallback: (){},
Space required `(){}` should be `() {}`

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/home/home_page.dart
> +                    /*    AppBarButtons().notification(
Remove commented code

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/meditation/starting_bell.dart
> +          icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/meditation/starting_bell.dart
> +          onClickCallback: ()=>Navigator.pop(context),
Spaces required `()=>Navigator.pop(context),` should be `() => Navigator.pop(context),`

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/mood_tracker/current_mood.dart
> +          icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/mood_tracker/current_mood.dart
> +          onClickCallback: ()=> Modular.to.pop(),
Space required `()=> Modular.to.pop(),` should be `() => Modular.to.pop(),`

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/mood_tracker/edit_mood.dart
> +          icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Also spece before `const`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/mood_tracker/edit_mood.dart
> +          onClickCallback: ()=> Modular.to.pop(),
Space required `()=> Modular.to.pop(),` should be `() => Modular.to.pop(),`

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/mood_tracker/mood_tracker_page.dart
> +            icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Also spece before `const`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/onboarding/onboarding_page.dart
> +          icon:const Icon(Icons.arrow_back),
Add space before `const`

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/playlist/add_to_playlist/add_to_playlist_page.dart
> +    /*    AppBarButtons().close(
Remove commented code

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/playlist/create_new_playlist/create_new_playlist_page.dart
> +          icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Also spece before `const`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/profile/current_user/edit_profile/edit_profile_page.dart
> +          icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Also spece before `const`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/profile/current_user/upload_audio/upload_audio_page.dart
> +          icon:const Icon(Icons.cancel, color: Colors.white) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Also spece before `const`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/profile/users_list/users_list_page.dart
> +            icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Also spece before `const`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/pages/wallet/wallet_restore.dart
> +          icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Also spece before `const`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/pages/wallet/wallet_seed_phrase.dart
> +          icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Also spece before `const`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/pages/wallet/wallet_seed_phrase.dart
> +        leading:CommonActionButton(
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/pages/wallet/wallet_seed_phrase.dart
> +          onClickCallback: ()=> Modular.to.pop(),
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/pages/wallet/wallet_terms_and_conditions.dart
> +          icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Also spece before `const`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/pages/wallet/wallet_terms_and_conditions.dart
> +          onClickCallback: ()=> Modular.to.pop(),
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/pages/wallet/wallet_verify_seed_phrase.dart
> +          icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Also spece before `const`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/pages/wallet/wallet_verify_seed_phrase.dart
> +          onClickCallback: ()=> Modular.to.pop(),
Add spcae

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/processing_transaction_page.dart
> +          onClickCallback: (){},
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/qrcode_reader_page.dart
> +          icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Also spece before `const`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/qrcode_reader_page.dart
> +          onClickCallback: ()=> Modular.to.pop(),
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/wallet_import_page.dart
> +        leading:CommonActionButton(
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/wallet_import_page.dart
> +          icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Also spece before `const`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/wallet_import_page.dart
> +          onClickCallback: ()=> Modular.to.pop(),
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/wallet_transfer_page.dart
> +            icon:ImageIcon(
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/wallet/pages/wallet/wallet_restore.dart
> +          onClickCallback: ()=> Modular.to.pop(),
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/profile/users_list/users_list_page.dart
> +            onClickCallback: ()=> Modular.to.pop(),
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/profile/current_user/upload_audio/upload_audio_page.dart
> +          onClickCallback: ()=> Modular.to.pop(),
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/profile/current_user/edit_profile/edit_profile_page.dart
> +          onClickCallback: ()=> Modular.to.pop(),
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/profile/current_user/edit_audio/edit_audio_page.dart
> +          icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Also spece before `const`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/profile/current_user/edit_audio/edit_audio_page.dart
> +          onClickCallback: ()=> Modular.to.pop(),
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/playlist/edit_playlist/edit_playlist_page.dart
> +          icon:const Icon(Icons.arrow_back) ,
Please format the code properly, unnesesary space `) ,` should be `),`
Also spece before `const`
Use default dart formating onFileSave

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/playlist/edit_playlist/edit_playlist_page.dart
> +        leading:CommonActionButton(
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/playlist/edit_playlist/edit_playlist_page.dart
> +          onClickCallback: ()=> Modular.to.pop(),
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/playlist/create_new_playlist/create_new_playlist_page.dart
> +        leading:CommonActionButton(
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/onboarding/onboarding_page.dart
> +          onClickCallback: ()=> Modular.to.pop(),
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/mood_tracker/mood_tracker_page.dart
> +            onClickCallback: ()=> Modular.to.pop(),
Add space

2020-09-10 10:20 UTC, AlexVegner commented on mobile/lib/modules/auth/register/register_with_sms/create_password/create_password_page.dart
> +      /*  AppBarButtons().back(
Remove commented code

2020-09-10 10:20 UTC, AlexVegner commented on core/lib/widgets/buttons/common_action_button.dart
> +  final OnClickCallback onClickCallback;
Use VoidCallback from Flutter SDK, use simple name like Flitted do `onPressed`, `onTap`, `onClick` 
It is obvious that this is a callback.

2020-09-14 15:23 UTC, AlexVegner requested changes

2020-09-14 15:23 UTC, AlexVegner commented on mobile/.gitignore
> +gradlew.bat
We need mobile/gradle/wrapper folder. 
So please fix it.

2020-09-14 15:23 UTC, AlexVegner commented on mobile/.gitignore
> +build.gradle
We need build.gradle file under  mobile/android and mobile/android/app, so please fix it.

2020-09-14 15:23 UTC, AlexVegner commented on mobile/.gitignore
> +local.properties
Check mobile/android/.gitignore it already have those rules.

2020-09-14 15:23 UTC, AlexVegner commented on .gitignore
> +.gradle/
Please make sure that those rules will relate only root folder.
sample
```
/.gradle
/.gradle
/gradlew
/gradlew.bat
/local.properties
```

2020-09-15 09:56 UTC, mob-dev commented on mobile/.gitignore
> +gradlew.bat
You mean, mobile/android/gradle/wrapper folder. Right?

2020-09-16 07:12 UTC, AlexVegner approved these changes

2020-09-16 07:12 UTC, merged