Feature/vijay change wallpaper
HighVibe/hvn pull request #353
Opened 2020-08-25 11:19 UTC by mob-dev

- Create Change Wallpaper page & Wallpaper preview page
- Save changed wallpaper in SharedPreferences

2020-08-31 14:42 UTC, AlexVegner commented on mobile/lib/modules/change_theme/widgets/wallpaper.dart
> +                showToast(message: 'Wallpaper changed successfully!!!');
Tost overlap button, looks not good. 
Romove it.

2020-08-31 14:43 UTC, AlexVegner commented on mobile/lib/modules/change_theme/widgets/wallpaper.dart
> +                showToast(message: 'Please select wallpaper');
User should not have option to not select one of background wallpaper
Remove showToast

2020-08-31 14:47 UTC, AlexVegner commented on mobile/lib/modules/change_theme/widgets/wallpaper.dart
> +import 'package:flutter_modular/flutter_modular.dart';
Wrong padding 
<img width="413" alt="Screenshot 2020-08-31 at 17 44 12" src="https://user-images.githubusercontent.com/1761175/91733298-080d0b00-ebb2-11ea-9b32-fc889d6d009a.png">

2020-09-04 10:45 UTC, mob-dev commented on mobile/lib/modules/change_theme/widgets/wallpaper.dart
> +  final sharedPreferences = Modular.get<SharedPreferences>();
Done

2020-09-07 16:29 UTC, AlexVegner requested changes

2020-09-07 16:29 UTC, AlexVegner commented on mobile/pubspec.yaml
> +  web3dart: ^1.2.3
Already presented in core, avoid to add same dependency to mobile or web if it presented in core
```
web3dart: ^1.2.3
google_sign_in: ^4.4.6
```

2020-09-14 08:00 UTC, AlexVegner approved these changes

2020-09-14 08:11 UTC, merged