Link all TextStyles with AppTheme
HighVibe/hvn pull request #380
Opened 2020-09-02 05:00 UTC by sudoosama

2020-09-07 09:30 UTC, AlexVegner requested changes
Changes required. 

Please create sample page and show all text styles form Style Guide like we agreed before in Telegram channel: 
```
Please create a page core/example/lib/pages/styles_guideline_page.dart in example project, and make sure that theme styles (from core project) works properly for example project.
```

2020-09-07 09:30 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            fontFamily: 'Arial',
fontFamily already defined in your theme style `bodyText2`

2020-09-07 09:30 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            fontFamily: 'Arial',
font Family: 'Arial' already defined in team, we don't need to redefine it here

2020-09-07 09:30 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            fontFamily: 'Arial',
font Family: 'Arial' already defined in team, we don't need to redefine it here

2020-09-07 09:30 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            fontFamily: 'Arial',
font Family: 'Arial' already defined in team, we don't need to redefine it here

2020-09-07 09:30 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            fontFamily: 'Arial',
font Family: 'Arial' already defined in team, we don't need to redefine it here

2020-09-07 09:30 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            fontFamily: 'Arial',
font Family: 'Arial' already defined in team, we don't need to redefine it here

2020-09-07 09:30 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            fontFamily: 'Arial',
font Family: 'Arial' already defined in team, we don't need to redefine it here

2020-09-07 09:30 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            fontFamily: 'Arial',
font Family: 'Arial' already defined in team, we don't need to redefine it here

2020-09-07 09:30 UTC, AlexVegner commented on core/lib/common/themes/app_theme.dart
> +      headline4: TextStyle(
Add styles:
```
 headline5: TextStyle(
        fontFamily: 'PlayFair',
        fontSize: 30,
        fontWeight: FontWeight.w700,
        fontStyle: FontStyle.normal,
        color: AppColors.primaryColor,
      ),
headline3: TextStyle(
        fontFamily: 'PlayFair',
        fontSize: 48,
        fontWeight: FontWeight.w700,
        fontStyle: FontStyle.normal,
        color: AppColors.primaryColor,
      ),

headline2: TextStyle(
        fontFamily: 'PlayFair',
        fontSize: 60,
        fontWeight: FontWeight.w700,
        fontStyle: FontStyle.normal,
        color: AppColors.primaryColor,
      ),

headline1: TextStyle(
        fontFamily: 'PlayFair',
        fontSize: 96,
        fontWeight: FontWeight.w700,
        fontStyle: FontStyle.normal,
        color: AppColors.primaryColor,
      ),
```

2020-09-07 09:30 UTC, AlexVegner commented on core/pubspec.yaml
> +  # firebase_auth_mocks:
Don't comment code, remove it if you feel that your line fix some issues.

2020-09-07 09:30 UTC, AlexVegner commented on core/pubspec.yaml
> +        - asset: assets/fonts/Nunito-Regular.ttf
Do we need Nunito-Regular.ttf  in our app?

2020-09-07 09:30 UTC, AlexVegner commented on mobile/lib/modules/guided_timer/show_guided_timer_list_items/show_guided_timer_list_items_page.dart
> +                    style: AppStyles.bold16White(context),
Do we need this changes?

2020-09-07 09:30 UTC, AlexVegner commented on mobile/lib/modules/guided_timer/show_guided_timer_list_items/show_guided_timer_list_items_page.dart
> +                    style: AppStyles.bold16White(context),
Do we need this changes?

2020-09-08 17:07 UTC, sudoosama commented on core/pubspec.yaml
> +        - asset: assets/fonts/Nunito-Regular.ttf
core/lib/common/themes/app_theme.dart
```
final TextStyle body1 = const TextStyle(
  fontFamily: 'Nunito',
  fontSize: 16,
  fontWeight: FontWeight.normal,
  fontStyle: FontStyle.normal,
);

```
In master branch we have Nunito font, previously when we are working with GoogleFonts Nunito was already in the Master branch while converting to GoogleFonts to External Font Files i though it will use for any future font family thats why i added, if we dont need this FontFamily so should I also deleted the above code from the `core/lib/common/themes/app_theme.dart` ?

2020-09-08 17:09 UTC, sudoosama commented on mobile/lib/modules/guided_timer/show_guided_timer_list_items/show_guided_timer_list_items_page.dart
> +                    style: AppStyles.bold16White(context),
Currently we dont have any `normal16` function to call from AppStyles.

2020-09-08 17:10 UTC, sudoosama commented on mobile/lib/modules/guided_timer/show_guided_timer_list_items/show_guided_timer_list_items_page.dart
> +                    style: AppStyles.bold16White(context),
Currently we dont have any `normal16` function to call from AppStyles.

2020-09-10 10:39 UTC, AlexVegner requested changes

2020-09-10 10:39 UTC, AlexVegner commented on hvn.code-workspace
> +		"dart.flutterSdkPath": "C:\\\\Program Files\\\\flutter\\\\flutter",
Please remove it. It can break work for other developers. Keep it in your user settings.

2020-09-10 12:40 UTC, merged