Implemented quick menu widget.
HighVibe/hvn pull request #383
Opened 2020-09-06 12:30 UTC by dkaera

2020-09-07 16:20 UTC, AlexVegner requested changes

2020-09-07 16:20 UTC, AlexVegner commented on mobile/lib/modules/home/widgets/quick_menu_item.dart
> +  QuickMenuItem.withText(this.icon, this.elevation, this.tooltip,
A lot of unnesesary constructore. Please update it with one constructor with named arguments
const QuickMenuItem() {
 @required this.elevation, 
  @required this.tooltip,
  @required this.onPressed, 
  this.hideOnClick = true,
  this.image,
  this.icon,
  this.text, 
  this.textColor,
}

2020-09-07 16:20 UTC, AlexVegner commented on mobile/lib/modules/home/widgets/quick_menu_item.dart
> +    text = null;
By default all fields are null, you don't need to initialize it with null.

2020-09-07 16:20 UTC, AlexVegner commented on mobile/lib/modules/home/widgets/quick_menu_item.dart
> +      this.itemCount})
Use last coma for good flutter formatting:
```dart
    ...
    this.itemCount,
  },
)
```

2020-09-07 16:20 UTC, AlexVegner commented on mobile/lib/modules/home/widgets/quick_menu_widget.dart
> +  const QuickMenuWidget(this._quickMenuItemList,
Use constructor with named parameters for all StatefulWidget / StatelessWidget widgets 
Google prefer to do it for all Flutter widgets.
```dart 
  const QuickMenuWidget({
    Key key,
    @required this.quickMenuItemList,
    this.fabAnimationStyle = AnimationStyle.defaultAnimation,
}) : super(key: key);

```

2020-09-07 16:20 UTC, AlexVegner commented on mobile/lib/modules/home/widgets/quick_menu_widget.dart
> +  final List<QuickMenuItem> _quickMenuItemList;
All class fields should be above constructors. 
Keep order: class fields, constructors, methods.

2020-09-07 16:20 UTC, AlexVegner commented on mobile/lib/modules/home/widgets/quick_menu_widget.dart
> +      QuickMenuWidgetState(_quickMenuItemList, _fabAnimationStyle);
Avoid to send StatefulWidget fields to State 
Use `widget.quickMenuItemList` and `widget.quickMenuItemList` inside State

2020-09-07 16:20 UTC, AlexVegner commented on mobile/lib/modules/home/widgets/quick_menu_widget.dart
> +  final List<QuickMenuItem> _quickMenuItemList;
remove it

2020-09-07 16:20 UTC, AlexVegner commented on mobile/lib/modules/home/widgets/quick_menu_widget.dart
> +  final AnimationStyle _fabAnimationStyle;
remove it

2020-09-07 16:20 UTC, AlexVegner commented on mobile/lib/modules/home/widgets/quick_menu_widget.dart
> +    setFabMenu(_quickMenuItemList);
Use `widget.quickMenuItemList` and `widget.quickMenuItemList` inside State

2020-09-07 16:23 UTC, AlexVegner requested changes

2020-09-07 16:23 UTC, AlexVegner commented on mobile/lib/modules/home/widgets/quick_menu_widget.dart
> +    _controller = AnimationController(
You need to dispose all controllers. in dispose method

2020-09-08 09:58 UTC, dkaera commented on mobile/lib/modules/home/widgets/quick_menu_item.dart
> +  double elevation;
applied

2020-09-08 09:58 UTC, dkaera commented on mobile/lib/modules/home/widgets/quick_menu_item.dart
> +  QuickMenuItem.withText(this.icon, this.elevation, this.tooltip,
applied

2020-09-08 09:59 UTC, dkaera commented on mobile/lib/modules/home/widgets/quick_menu_item.dart
> +    text = null;
removed as not used

2020-09-10 11:00 UTC, AlexVegner approved these changes

2020-09-10 11:00 UTC, AlexVegner commented on mobile/lib/modules/home/widgets/quick_menu_item.dart
> +                colors: [Color(0xFF666CCC), Color(0xFF66CCCC)])),
Please move all colors and gradient list to AppColors

2020-09-10 11:00 UTC, AlexVegner commented on mobile/lib/modules/home/widgets/quick_menu_widget.dart
> +                            colors: [Color(0xFF666CCC), Color(0xFF66CCCC)])),
Please move all colors and gradient list to AppColors

2020-09-10 11:00 UTC, AlexVegner commented on mobile/lib/modules/home/widgets/quick_menu_item.dart
> +              colors: [Color(0xFF666CCC), Color(0xFF66CCCC)])),
Please move all colors and gradient list to AppColors

2020-09-10 11:00 UTC, merged