Update all hardcoded TextStyle. All text style should relate on AppTheme, or use / extend common style
HighVibe/hvn pull request #400
Opened 2020-09-13 22:22 UTC by sudoosama

2020-09-14 15:01 UTC, AlexVegner requested changes
Please make shure that you fixed all placess with hardcoded `TextStyle(` and `Color(0x`

2020-09-19 10:31 UTC, AlexVegner requested changes

2020-09-19 10:31 UTC, AlexVegner commented on mobile/lib/modules/playlist/edit_playlist/edit_playlist_page.dart
> +              controller: _titleController,
Use dart file format for dart formation. 
We have it in vscode workspace configuration. 
- Automatic dart file formating, 
- automatic import optimization.

2020-09-19 10:31 UTC, AlexVegner commented on mobile/lib/modules/playlist/edit_playlist/edit_playlist_page.dart
> +              controller: _descriptionController,
Use dart file format for dart formation.

2020-09-19 10:31 UTC, AlexVegner commented on mobile/lib/modules/playlist/widgets/ui_utils.dart
> +Widget snackBarLight({@required String message, BuildContext context}) {
BuildContext should be first argument for all widget build methods where we need it.

2020-09-19 10:31 UTC, AlexVegner commented on mobile/lib/modules/profile/widgets/profile_input_field.dart
> +                  contentPadding: const EdgeInsets.symmetric(vertical: 20),
Use dart file format for dart formation.

2020-09-19 10:31 UTC, AlexVegner commented on mobile/lib/modules/wallet/components/transactions/transaction_list.dart
> +                leading:const Icon(Icons.info),
Use dart file format for dart formation.
`leading:const` should be `leading: const`

2020-09-19 10:31 UTC, AlexVegner commented on mobile/lib/modules/wallet/components/wallet/balance.dart
> +                            padding:const  EdgeInsets.fromLTRB(20, 10, 20, 0),
Use dart file format for dart formation.
`const  EdgeInsets` should be `const EdgeInsets` (one space)

2020-09-19 10:31 UTC, AlexVegner commented on mobile/lib/modules/wallet/pages/auth/passcode/passcode_page.dart
> +style: AppStyles.normal18WithColor(context,
Use dart file format for dart formation.

2020-09-19 10:31 UTC, AlexVegner commented on mobile/lib/modules/wallet/components/wallet/balance.dart
> +                              padding:const EdgeInsets.fromLTRB(20, 10, 20, 0),
Use dart file format for dart formation.
`padding:const` should be `padding: const`

2020-09-19 10:31 UTC, AlexVegner commented on mobile/lib/widgets/tags/tag_item.dart
> +    _getTextStyle(context);
Epic usage)
You need to use result of _getTextStyle(context);...

2020-09-22 08:34 UTC, sudoosama commented on mobile/lib/modules/profile/widgets/profile_input_field.dart
> +                  contentPadding: const EdgeInsets.symmetric(vertical: 20),
Okay

2020-10-01 18:25 UTC, AlexVegner requested changes

2020-10-01 18:25 UTC, AlexVegner commented on mobile/lib/modules/profile/current_user/create_post/edit_post_page.dart
> +          style: AppStyles.normal14White(context),
Should be `bold`

2020-10-01 18:25 UTC, AlexVegner commented on mobile/lib/modules/meditation/past_meditation.dart
> +                            style: AppStyles.normal16WithColor(context,
Should be `bold`

2020-10-01 18:25 UTC, AlexVegner commented on mobile/lib/modules/live/components/widgets/add_description_widget.dart
> +      style: AppStyles.normal16White(context),
Use `fontSize` parameter

2020-10-01 18:25 UTC, AlexVegner commented on mobile/lib/modules/discover/videos/video_card.dart
> +                backgroundColor: AppColors.backgroundColor,
it should be background color with transparency 0x40

2020-10-01 18:25 UTC, AlexVegner commented on mobile/lib/modules/discover/live_now/live_card.dart
> +                      backgroundColor: AppColors.backgroundColor,
It should be backgroundColor with transparency 0x40

2020-10-01 18:25 UTC, AlexVegner commented on mobile/lib/modules/discover/audios/audio_card.dart
> +            color: Colors.black,
it should be black with transparency 0x50

2020-10-01 18:25 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            fontSize: 15,
fontSize: 15, ???

2020-10-01 18:25 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            fontSize: 42,
It should have normal weight not bold

2020-10-01 18:25 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
>              fontSize: 24,
bold20PlayfairWhite should have fontSize: 20 not 24

2020-10-01 18:25 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            color: Colors.white,
You should use color parameter here

2020-10-01 18:25 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            color: Colors.white,
Uou should use color parameter here

2020-10-01 18:25 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            color: Colors.white,
You should use color parameter here

2020-10-01 18:25 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            color: Colors.white,
You should use color parameter here

2020-10-01 18:25 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            color: Colors.white,
You should use color parameter here

2020-10-01 18:25 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            color: Colors.white,
You should use `color`

2020-10-01 18:25 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +            color: Colors.white,
You should use color parameter here

2020-10-01 18:25 UTC, AlexVegner commented on core/lib/common/themes/app_styles.dart
> +      Theme.of(context).textTheme.overline.copyWith(color: Colors.white);
you should use color parameter here

2020-10-05 07:57 UTC, AlexVegner commented
To many issues in PR. To risky for merge. 
PR closed.

2020-10-05 07:57 UTC, closed without merging