VC-402: Livestream integration with Agora. Basic.
HighVibe/hvn pull request #416
Opened 2020-09-18 10:40 UTC by vladimircores

This is basic working version of Livestream feature. No branded design for UI, only simple controls. This can be already used and open a way to implement posts about livestream in other parts of the application.

2020-09-18 10:43 UTC, vladimircores commented
This is how it works:
![agora_video_live](https://user-images.githubusercontent.com/442111/93588994-7de3e580-f9ac-11ea-90ec-0caa590d9220.gif)

2020-09-18 10:52 UTC, vladimircores commented
And this is how it works:
![agora_video_live_10fps-min](https://user-images.githubusercontent.com/442111/93589861-cc45b400-f9ad-11ea-83ba-595ebc38f627.gif)

2020-09-19 09:25 UTC, AlexVegner requested changes
Multiple changes required
Also please check linter it show errors for your PR

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/LiveStore.dart
> +import 'package:agora_rtc_engine/rtc_engine.dart';
By Dart convention file and folder names should be in snake case.
And please use _controller for mobex stores 
So please move it to core/lib/controllers/live/live_controller.dart

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/LiveStore.dart
> +abstract class _LiveStore with Store {
Rename it ad LiveController

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/LiveStore.dart
> +  ClientStore _clientStore;
Please inject all dependencies. and keep them final by default.

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/LiveStore.dart
> +      _masterStore = MasterStore();
Please inject it, to be sure that we could write unit test in future.

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/LiveStore.dart
> +      _clientStore = ClientStore();
Please inject it, to be sure that we could write unit test in future.

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/RoomsStore.dart
> +import 'dart:async';
By Dart convention file and folder names should be in snake case: `room_controller.dart`

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/RoomsStore.dart
> +class RoomsStore = _RoomsStore with _$RoomsStore;
Rename it as RoomController

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/live/AgoraStore.dart
> +import 'dart:async';
By Dart convention file and folder names should be in snake case: `agora_controller.dart`

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/live/AgoraStore.dart
> +class AgoraStore with LiveStatusDispatcher {
Use class name AgoraController

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/live/AgoraStore.dart
> +    if (_engine == null) return;
Do we need 

```dart
 if (_engine == null) return;
```

each time when we use `_engine?

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/live/ClientStore.dart
> +import 'dart:async';
By Dart convention file and folder names should be in snake case: live_client_controller.dart

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/live/ClientStore.dart
> +class ClientStore = _ClientStore with _$ClientStore;
Rename it with LiveClientController

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/live/MasterStore.dart
> +import 'dart:async';
By Dart convention file and folder names should be in snake case: live_master_controller.dart

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/live/MasterStore.dart
> +class MasterStore = _MasterStore with _$MasterStore;
Rename it with LiveMasterController

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/store/live/mixin/LiveStatusDispatcher.dart
> +import 'dart:async';
By Dart convention file and folder names should be in snake case `live_status_dispatcher.dart`

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/model/vo/TokenVO.dart
> +class TokenVO {
Please move it to core/lib/models/live/live_token.dart
Rename class LiveToken

2020-09-19 09:25 UTC, AlexVegner commented on mobile/lib/modules/live/components/pages/live.page.dart
> +  Future<bool> _onBackPressed(context, LiveStore liveStore) async {
User can click on Android hardware back button or use back gesture on iOS. 
We need to handle the case. 
Please handle it or write `//TODO` for it.

2020-09-20 09:38 UTC, vladimircores commented on mobile/lib/modules/live/model/store/live/enum/LiveStatus.dart
> +enum LiveStatus {
Done.

2020-09-20 13:27 UTC, vladimircores commented on mobile/pubspec.yaml
> +  mock_cloud_firestore:
Yeah, I forgot to revert it back, thanks for pointing it.

2020-09-20 13:28 UTC, vladimircores commented on mobile/lib/modules/live/model/store/live/MasterStore.dart
> +            // DocumentReference peerDocument = _peersStore.peersCollection.doc(
It's not needed for now, and can be grabbed from original version. Removed.

2020-09-20 13:31 UTC, vladimircores commented on mobile/lib/modules/live/components/pages/live/live.client.widget.dart
> +  // Future<void> _onClientDisposed(context) async {
It's not needed for now, can be returned from original code if needed. Removed.

2020-09-20 13:49 UTC, vladimircores commented on mobile/lib/modules/live/components/pages/live/live.master.widget.dart
> +  static const _tsMessage = TextStyle(color: Colors.red, fontSize: 14.0);
Thanks for advice, I will in the future, these styles is temporal and will be removed.

2020-09-20 13:49 UTC, vladimircores commented on mobile/lib/modules/live/components/pages/rooms.page.dart
> +  static const COLOR_BACK = Colors.white;
Thanks for advice, I will in the future, these styles is temporal and will be removed.

2020-09-20 13:49 UTC, vladimircores commented on mobile/lib/modules/live/components/pages/rooms.page.dart
> +  static const _textStyle_Message
Thanks for advice, I will in the future, these styles is temporal and will be removed.

2020-09-20 13:54 UTC, vladimircores commented on mobile/lib/modules/live/live_page.dart
> +class LivePage2 extends StatefulWidget {
I would like to use it as a reference for RoomsPage implementation. Will keep it for now with postfix in name Template.

2020-09-20 15:09 UTC, vladimircores commented on mobile/lib/modules/live/model/store/live/AgoraStore.dart
> +    if (_engine == null) return;
It was made to avoid silent try/catch but now change to use it.

2020-09-22 13:52 UTC, AlexVegner approved these changes

2020-09-22 13:52 UTC, merged